jobs:
  deploy:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - run: node --version
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the node-orb
  welcome: circleci/node@4.1.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "electron-build"
  electron-build:
    jobs:
      - deploy
